config/routes.rb
class MainSite
  def self.matches?(request)
    request.subdomain.blank? || request.subdomain == 'www'
  end
end

Subscriptions::Application.routes.draw do
  resources :routes

  resources :problems

  devise_for :saas_admins

  constraints MainSite do
    root :to => "content#index"
    
    match '/signup' => 'accounts#plans', :as => 'plans'
    match '/signup/d/:discount' => 'accounts#plans'
    match '/signup/thanks' => 'accounts#thanks', :as => 'thanks'
    match '/signup/create/:discount' => 'accounts#create', :as => 'create', :defaults => { :discount => nil }
    match '/signup/:plan/:discount' => 'accounts#new', :as => 'new_account'
    match '/signup/:plan' => 'accounts#new', :as => 'new_account'
    
    match '/content/:action' => 'content'
  end

  root :to => "accounts#dashboard"

  devise_for :users

  resources :users
  resource :account do 
    member do
      get :dashboard, :thanks, :plans, :canceled
      match 'billing' => "accounts#billing"
      match 'paypal' => "accounts#paypal"
      match 'plan' => "accounts#plan"
      match 'plan_paypal' => "accounts#plan_paypal"
      match 'cancel' => "accounts#cancel"
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :account
  has_many :routes

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable, :registerable and :timeoutable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :encryptable, :authentication_keys => [:email, :account_id]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_protected :account_id

  # Putting Devise validations here rather than using :validatable in the call to #devise
  # to get validations of the login attribute
  validates_presence_of   :email
  validates_uniqueness_of :email, :scope => :account_id, :case_sensitive => false
  validates_format_of     :email, :with  => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i

  with_options :if => :password_required? do |v|
    v.validates_presence_of     :password
    v.validates_confirmation_of :password
    v.validates_length_of       :password, :within => 3..20, :allow_blank => true
  end

  def last_climb_day
    routes.map(&:created_at).sort.last.to_s(:short) if routes.present?
  end

  def last_days_score
    routes.group_by{|r| r.created_at.to_date }.sort.last[1].sum{|r| r.problem.points } if routes.present?
  end

  protected

    # Checks whether a password is needed or not. For validations only.
    # Passwords are always required if it's a new record, or if the password
    # or confirmation are being set somewhere.
    def password_required?
      !persisted? || !password.nil? || !password_confirmation.nil?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  inherit_resources

  before_filter :authenticate_user!
  before_filter :authorized?
  before_filter :check_user_limit, :only => :create
  
  def create
    create! { users_url }
  end
  
  def update
    update! { users_url }
  end
  
  protected

    # This is the way to scope everything to the account belonging
    # for the current subdomain in InheritedResources.  This
    # translates into
    # @user = current_account.users.build(params[:user]) 
    # in the new/create actions and
    # @user = current_account.users.find(params[:id]) in the
    # edit/show/destroy actions.
    def begin_of_association_chain
      current_account
    end
    
    def authorized?
      redirect_to new_user_session_url unless (user_signed_in? && self.action_name == 'index') || admin?
    end
    
    def check_user_limit
      redirect_to new_user_url if current_account.reached_user_limit?
    end
  
end

app/views/users/_form.html.erb
<%= simple_form_for @user, form_options do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>

  <%= f.button :submit, class: "btn-success" %>
<% end %>

app/views/users/_header.html.erb
<div class="page-header clearfix">
  <h1 class="pull-left">Users</h1>

  <div class="btn-group pull-right">
    <%= link_to users_path, class: "btn btn-default #{'active' if current_page? users_path}" do %>
      <span class="glyphicon glyphicon-align-left"></span>
    <% end %>

    <%= link_to new_user_path, class: "btn btn-default #{'active' if current_page? new_user_path}" do %>
      <span class="glyphicon glyphicon-plus"></span>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<%= render partial: "users/header" %>

<%= render "form" %>

app/views/users/index.html.erb
<%= render partial: "users/header" %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Manage </th>
    </tr>
  </thaed>

  <tbody>
    <%  current_account.users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td>
          <%= link_to edit_user_path(user) do %>
            <span class="glyphicon glyphicon-pencil"></span>
          <% end %>

          <%= link_to user, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<%= render partial: "users/header" %>

<% if current_account.reached_user_limit? %>
  <p>You have reached the maximum number of users you can have with your account level.  You can either delete some of your users or <a href="/account/plan">upgrade your account</a> to be able to create a new user.</p>
<% else %>
  <%= render "form" %>
<% end %>