config/routes.rb
class MainSite
  def self.matches?(request)
    request.subdomain.blank? || request.subdomain == 'www'
  end
end

Subscriptions::Application.routes.draw do
  resources :routes

  resources :problems

  devise_for :saas_admins

  constraints MainSite do
    root :to => "content#index"
    
    match '/signup' => 'accounts#plans', :as => 'plans'
    match '/signup/d/:discount' => 'accounts#plans'
    match '/signup/thanks' => 'accounts#thanks', :as => 'thanks'
    match '/signup/create/:discount' => 'accounts#create', :as => 'create', :defaults => { :discount => nil }
    match '/signup/:plan/:discount' => 'accounts#new', :as => 'new_account'
    match '/signup/:plan' => 'accounts#new', :as => 'new_account'
    
    match '/content/:action' => 'content'
  end

  root :to => "accounts#dashboard"

  devise_for :users

  resources :users
  resource :account do 
    member do
      get :dashboard, :thanks, :plans, :canceled
      match 'billing' => "accounts#billing"
      match 'paypal' => "accounts#paypal"
      match 'plan' => "accounts#plan"
      match 'plan_paypal' => "accounts#plan_paypal"
      match 'cancel' => "accounts#cancel"
    end
  end

end

app/models/saas_admin.rb
class SaasAdmin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable, :encryptable, 
         :recoverable, :rememberable, :trackable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/saas_admin/accounts_controller.rb
class SaasAdmin::AccountsController < SaasAdminController
  inherit_resources
  
  protected
  
    def collection
      @accounts = Account.paginate(:include => :subscription, :page => params[:page], :per_page => 30, :order => 'accounts.name')
    end
  
end

app/helpers/saas_admin/accounts_helper.rb
module SaasAdmin::AccountsHelper
end

app/views/saas_admin/shared/_navigation.html.erb
<ul>
  <li><%= link_to('Subscriptions', saas_admin_subscriptions_path) %></li>
  <li><%= link_to('Accounts', saas_admin_accounts_path) %></li>
  <li><%= link_to('Plans', saas_admin_subscription_plans_path) %></li>
  <li><%= link_to('Discounts', saas_admin_subscription_discounts_path) %></li>
  <li><%= link_to('Affiliates', saas_admin_subscription_affiliates_path) %></li>
  <li><%= link_to("Log out #{current_saas_admin.email}", destroy_saas_admin_session_path) %></li>
</ul>