config/routes.rb
class MainSite
  def self.matches?(request)
    request.subdomain.blank? || request.subdomain == 'www'
  end
end

Subscriptions::Application.routes.draw do
  resources :routes

  resources :problems

  devise_for :saas_admins

  constraints MainSite do
    root :to => "content#index"
    
    match '/signup' => 'accounts#plans', :as => 'plans'
    match '/signup/d/:discount' => 'accounts#plans'
    match '/signup/thanks' => 'accounts#thanks', :as => 'thanks'
    match '/signup/create/:discount' => 'accounts#create', :as => 'create', :defaults => { :discount => nil }
    match '/signup/:plan/:discount' => 'accounts#new', :as => 'new_account'
    match '/signup/:plan' => 'accounts#new', :as => 'new_account'
    
    match '/content/:action' => 'content'
  end

  root :to => "accounts#dashboard"

  devise_for :users

  resources :users
  resource :account do 
    member do
      get :dashboard, :thanks, :plans, :canceled
      match 'billing' => "accounts#billing"
      match 'paypal' => "accounts#paypal"
      match 'plan' => "accounts#plan"
      match 'plan_paypal' => "accounts#plan_paypal"
      match 'cancel' => "accounts#cancel"
    end
  end

end

app/models/route.rb
class Route < ActiveRecord::Base
  belongs_to :user
  belongs_to :problem
  attr_accessible :user_id, :problem_id, :notes
end

app/controllers/routes_controller.rb
class RoutesController < InheritedResources::Base
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/routes/_form.html.erb
<%= simple_form_for @route, form_options do |f| %>
  <%= f.input :user_id, collection: current_account.users, selected: current_user %>
  <%= f.input :problem_id, collection: current_account.problems %>
  <%= f.input :notes, as: :text, input_html: { rows: 3 } %>

  <%= f.button :submit, class: "btn-success" %>
<% end %>

app/views/routes/_header.html.erb
<div class="page-header clearfix">
  <h1 class="pull-left">Routes</h1>

  <div class="btn-group pull-right">
    <%= link_to routes_path, class: "btn btn-default #{'active' if current_page? routes_path}" do %>
      <span class="glyphicon glyphicon-align-left"></span>
    <% end %>

    <%= link_to new_route_path, class: "btn btn-default #{'active' if current_page? new_route_path}" do %>
      <span class="glyphicon glyphicon-plus"></span>
    <% end %>
  </div>
</div>

app/views/routes/edit.html.erb
<%= render partial: "routes/header" %>

<%= render "form" %>

app/views/routes/index.html.erb
<%= render partial: "routes/header" %>

<table class="table">
  <thead>
    <tr>
      <th>User</th>
      <th>Problem</th>
      <th>Notes</th>
      <th>Day</th>
      <th>Manage </th>
    </tr>
  </thaed>

  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td><%= route.user.name %></td>
        <td><%= route.problem.name %></td>
        <td><%= route.notes %></td>
        <td><%= route.created_at.to_date.to_s(:short) %></td>
        <td>
          <%= link_to edit_route_path(route) do %>
            <span class="glyphicon glyphicon-pencil"></span>
          <% end %>

          <%= link_to route, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/routes/new.html.erb
<%= render partial: "routes/header" %>

<%= render "form" %>