config/routes.rb
class MainSite
  def self.matches?(request)
    request.subdomain.blank? || request.subdomain == 'www'
  end
end

Subscriptions::Application.routes.draw do
  resources :routes

  resources :problems

  devise_for :saas_admins

  constraints MainSite do
    root :to => "content#index"
    
    match '/signup' => 'accounts#plans', :as => 'plans'
    match '/signup/d/:discount' => 'accounts#plans'
    match '/signup/thanks' => 'accounts#thanks', :as => 'thanks'
    match '/signup/create/:discount' => 'accounts#create', :as => 'create', :defaults => { :discount => nil }
    match '/signup/:plan/:discount' => 'accounts#new', :as => 'new_account'
    match '/signup/:plan' => 'accounts#new', :as => 'new_account'
    
    match '/content/:action' => 'content'
  end

  root :to => "accounts#dashboard"

  devise_for :users

  resources :users
  resource :account do 
    member do
      get :dashboard, :thanks, :plans, :canceled
      match 'billing' => "accounts#billing"
      match 'paypal' => "accounts#paypal"
      match 'plan' => "accounts#plan"
      match 'plan_paypal' => "accounts#plan_paypal"
      match 'cancel' => "accounts#cancel"
    end
  end

end

app/views/layouts/_flash.html.erb
<% if notice.present? %>
  <div class="alert alert-info">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
    <%= notice %>
  </div>
<% end %>

<% if alert.present? %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to Saas::Config.app_name, root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Routes", routes_path %></li>
        <li><%= link_to "Problems", problems_path if admin? %></li>
        <li><%= link_to "Users", users_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <%= link_to "#", class: "dropdown-toggle", data: { toggle: "dropdown" } do %>
            Account <b class="caret"></b>
          <% end %>

          <ul class="dropdown-menu">
            <li><%= link_to "Edit account", edit_account_url %></li>
            <li><%= link_to "Change plan", plan_account_url %></li>
            <li><%= link_to "Billing info", billing_account_url %></li>
            <li><%= link_to "Cancel plan", cancel_account_url %></li>
          </ul>
        </li>

        <li><%= link_to "Log out", destroy_user_session_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title><%= @page_title ? "#{@page_title} | #{ Saas::Config.app_name }" : Saas::Config.app_name %></title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />

    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>

    <%= csrf_meta_tags %>

		<%= yield :head %>
	</head>

	<body class="<%= controller.controller_path.gsub('/', ' ') %>">
    <%= render partial: "layouts/header" %>


    <div id="wrapper" class="container">
      <div class="row">
        <div class="col-md-12">
          <%= render partial: "layouts/flash" %>

          <%= yield %>
        </div>
      </div>
    </div>
	</body>
</html>